# GitHub shows a "Sponsor" button on the repository once the account has a
# Sponsors profile (decision 10: a small Sponsors link beside the licence).
# Until the profile exists this file is inert.
github: OytunOnal
